# Generated by Django 3.1.4 on 2020-12-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_path', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('translate_code', models.CharField(max_length=250, verbose_name='验证码')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
